---

name: Discourier
description: Write to a Discord webhook.

branding:
  icon: bell
  color: green

inputs:
  url:
    description: The webhook endpoint to write to.
    required: yes

  name:
    description: The username to identify as with Discord.
    default: Action Bot 900

  avatar:
    description: The URL of the avatar to use for the message.

  level:
    description: The notification level to use.
    default: notice

  title:
    description: Set the title of the notification.

  message:
    description: The message contents to send.
    required: yes

  format:
    description: Apply the standard message template.
    default: no

runs:
  using: docker
  image: Dockerfile
