---

name: Discord Webhook
description: Write to a Discord webhook.

inputs:
  webhook-url:
    description: The webhook endpoint to write to.
    required: yes

  username:
    description: Username to identify as with Discord.
    default: Action Bot 900

  message:
    description: Message to write to the webhook.
    default: Hello, world!

  avatar:
    description: URL of the avatar to use for the message.

runs:
  using: docker
  image: Dockerfile
