---

name: Discord Webhook
description: Write to a Discord webhook.

inputs:
  webhook-url:
    description: The webhook endpoint to write to.
    required: yes

  username:
    description: Username to identify as with Discord.
    default: Action Bot 900

  avatar:
    description: URL of the avatar to use for the message.

  message:
    description: Send a plain message to the webhook.

  debug:
    description: Send a debug message to the webhook.

  error:
    description: Send an error message to the webhook.

  notice:
    description: Send an informational notice to the webhook.

  warn:
    description: Send a warning message to the webhook.

runs:
  using: docker
  image: Dockerfile
