---

name: discord-webhook-ci-pipeline

on:
  push:
    branches:
      - stable

    paths-ignore:
      - .gitignore
      - LICENSE
      - README.md

jobs:
  manufacture:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./
        with:
          url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          name: Build Reporter
          level: debug
          title: Build Status
          message: This is a formatted debug message.
          format: yes

      - uses: ./
        with:
          url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          name: Build Reporter
          level: notice
          title: Build Status
          message: This is a formatted notice message.
          format: yes

      - uses: ./
        with:
          url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          name: Build Reporter
          level: warning
          title: Build Status
          message: This is a formatted warning message.
          format: yes

      - uses: ./
        with:
          url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          name: Build Reporter
          level: error
          title: Build Status
          message: This is a formatted error message.
          format: yes

      - uses: ./
        with:
          url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          name: Build Reporter
          level: debug
          title: Build Status
          message: This is a debug message.

      - uses: ./
        with:
          url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          name: Build Reporter
          level: notice
          title: Build Status
          message: This is a notice message.

      - uses: ./
        with:
          url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          name: Build Reporter
          level: warning
          title: Build Status
          message: This is a warning message.

      - uses: ./
        with:
          url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          name: Build Reporter
          level: error
          title: Build Status
          message: This is an error message.
